### ISSUE TITLE
gltf: Animation and transformation issues

### ISSUE THREAD

**Issue by tkazik** [BabylonJS/Exporters#58]
Hi folks

I recently discovered this exporter for 3ds max and thought is was the solution to all my issues :)
I tried both 3ds max versions (2015/16 and 2017), but the resulting gltf/glb get twisted up:

![a319_animation_transformations](https://user-images.githubusercontent.com/15689124/34711121-66ded1b4-f51e-11e7-8d85-5b00b8361758.png)

Any ideas, why this is happening? The model han be found here:
[A319_gen.zip](https://github.com/BabylonJS/Exporters/files/1614351/A319_gen.zip)

The twist looks quite similar to the .fbx export I get when using the built-in fbx exporter from 3ds max 2016. The fbx exporter in version 2018 solved these issues for me. I know there is work in progress on the 2018 babylonjs-exporter as well...so this might solve also this issue. Or is this not connected?

Thanks for your hints!

**Comment by deltakosh** [comment]
If fbx exporter has the same issue, I'm afraid this is not something we can tackle at exporter level.
Support for 3dsmax 2018 is coming soon, will see if it helps

**Comment by noalak** [comment]
Hi tkazik,

No miracle solution :(
You can fix transform issue but animations are deleted in the process.

Here is the pipeline:
- select all nodes, delete their animations
- break the parenty relation between 'main_gear_leg_rh', 'main_gear_leg_lh', 'nose_leg' and their children (those relations seem to cause some issues)
- select all nodes, in the Tool tab of the Command panel choose 'Reset XForm'. Transformations should remain unchanged.
- restore parenty relation (if required)
- flip normals of some meshes (nacelles around engines, wings...)
- export

**Comment by tkazik** [comment]
Thank you for your quick reply, deltakosh and noalak!
@noalak Good to know, there is a fix available, although it includes a bit of work.
The parenty relation should not pose any problems thereafter, right? Just curious: How can you tell that these seem to cause issues?
@deltakosh I have quite some hope, that the [exporter of 2018](https://github.com/BabylonJS/Exporters/issues/6) might have the fix: The .fbx exporter of 2018 seems to be able to handle the export correctly: 
![fbx_2017_vs_2018](https://user-images.githubusercontent.com/15689124/34770219-969dbf04-f600-11e7-8431-5aa4936c46bd.png)
The gltf exported by 3ds max looks surprisingly similar the the exported fbx in 2017.
Also being curious: Is the exporter using the fbx exporter 'under the hood'?

Here you find the fbx, if needed:
[FBX_2017_vs_2018.zip](https://github.com/BabylonJS/Exporters/files/1618533/FBX_2017_vs_2018.zip)

**Comment by noalak** [comment]
Ignoring step 2 results in wheels being slided down for an unknown reason after ResetXForm.
Once ResetXForm is done, feel free to restore hierarchy as it was to ease animation process or let them unattached.

**Comment by deltakosh** [comment]
I'm gonna try to compile the max2018 version today

**Comment by deltakosh** [comment]
(And btw we are not using FBX exporter :))

**Comment by tkazik** [comment]
Thanks, awesome! Looking forward to it and keep my fingers crossed :)

**Comment by YangAndI** [comment]
I need your help,the  y-axis and z-axis is swap when i export the model from 3dsMAX.Thanks!

**Comment by deltakosh** [comment]
Please use the forum for questions :)

**Comment by tkazik** [comment]
Short update and one (hopefully last) question:

We fixed our model according the the "no miracle solution" by @noalak, which was more work for our designer than expected. [This](https://knowledge.autodesk.com/support/3ds-max/troubleshooting/caas/sfdcarticles/sfdcarticles/Non-uniform-scale-causes-rotation-issues-with-linked-geometry-in-3ds-Max.html) seems to be our error/issue/mistake, as described on the 3ds max page.

The corrected model now exports nicely to gltf/glb and is displayed perfectly in these two viewers:

https://gltf-viewer.donmccurdy.com
http://sandbox.babylonjs.com

However, one viewer is still having troubles and unfortunately it is exactly this viewer that we need, as we are working with [Cesium](https://cesium.com/index.html):

https://www.virtualgis.io/gltfviewer

Now my question: Is the model ok? Do you discover any flaws in it? The model looks flipped, as though the normals are inverted. Or do you think it is rather an issue with the viewer?

The files of the model are [here](https://github.com/BabylonJS/Exporters/files/1640131/A319_fixed.zip).

Thank you very much for your help!

PS: Thank you very much for [this](https://github.com/BabylonJS/Exporters/pull/63) feature...very helpful and works perfectly!

**Comment by deltakosh** [comment]
Hello!
you can try to run the model inside the gltf validator: https://github.com/KhronosGroup/glTF-Validator

**Comment by YangAndI** [comment]
What is "Autodesk.Max.IGameConversionManager.CoordSystem.D3d“ this? And why the W = -meshRotation.W? And why do these "rotation = new float[] { 0, (float)Math.PI, 0 }, scaling = new float[] { 1, 1, -1 }"

**Comment by Selmar** [comment]
The rotation and negative scale is to convert from a left-handed to a right-handed coordinate system.

It's definitely possible to convert all output data instead of applying a root matrix, but this method was easier, I assume.

I think the conversionmanager is leftover code from an idea to do the conversion properly.

**Comment by noalak** [comment]
I can't imagine the disappointment of your graphic designer when he saw issues are still there.

The inverted normal issue is related to [this gltf feature](https://github.com/BabylonJS/Babylon.js/pull/3399).
BabylonJS and ThreeJS handle it correctly while Cesium doesn't.

The exporter currently inverse Y and Z axis by setting a negative scale, thus negative determinant.
We are planning to change the way the inversion is done (at object level rather than global) as it causes other flip issues with rigged meshes.

For now, find attached the [binaries](https://github.com/BabylonJS/Exporters/files/1642572/Max2Babylon-0.34.0_noNormalFlip.zip) for the 3ds max exporter without the normal flip.

Stay tunned for exporter update. In the meantime, keep saying to your designer that everything is gonna be all right.

**Comment by tkazik** [comment]
Perfect @noalak, thank you very much for the binaries, now everything is fine!
I reported this issue also in the Cesium forum, where I got an answer that might help you:

https://groups.google.com/forum/#!topic/cesium-dev/Ktc9vwJiiTU

**Comment by deltakosh** [comment]
Good catch..Perhaps we are exporting the faces with the wrong winding order

**Comment by tkazik** [comment]
The new exporter version 0.36 combined together with 3ds max 2018 also seems to invert some meshes, see:
![new_flipped_meshes](https://user-images.githubusercontent.com/15689124/35502702-1ba43ffc-04de-11e8-9e8d-6c5496356f30.png)
The binaries without normal flip version 0.34 and 3ds max 2017 work fine on the model.
Any ideas why the new version is not running poperly?
Thx!

PS: Also the general normal flip issue is still present...

**Comment by noalak** [comment]
Last version does not fix normal flip issue encountered in Cesium.

This is something we are aware of and will be fixed soon. Stay tunned, this issue will be pinged when a pull request fixes it.

**Comment by tkazik** [comment]
Perfect, thank you very much! Now Cesium displays the model correctly.
Some surfaces are still inverted, but I guess that originates from [this issue].(https://github.com/BabylonJS/Exporters/issues/90)
